OnlineShoppingStore/Controllers/DetalleProductoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineShoppingStore.DAL;

namespace OnlineShoppingStore.Controllers
{
    public class DetalleProductoesController : Controller
    {
        private VentasEntities1 db = new VentasEntities1();

        // GET: DetalleProductoes
        public ActionResult Index()
        {
            var detalleProducto = db.DetalleProducto.Include(d => d.Producto);
            return View(detalleProducto.ToList());
        }
        public ActionResult listas()
        {
            return View();
        }

        public ActionResult detalleProducto( int id)
        {
            var filtro = db.DetalleProducto.Where(detalle => detalle.Producto_idProducto==id);
            ViewBag.Producto_talla = new SelectList(filtro, "Talla", "Talla");
            return View(filtro);
        }
        // GET: DetalleProductoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DetalleProducto detalleProducto = db.DetalleProducto.Find(id);
            if (detalleProducto == null)
            {
                return HttpNotFound();
            }
            return View(detalleProducto);
        }

        // GET: DetalleProductoes/Create
        public ActionResult Create()
        {
            ViewBag.Producto_idProducto = new SelectList(db.Producto, "idProducto", "nombreProducto");
            return View();
        }

        // POST: DetalleProductoes/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idDetalleProducto,Talla,CantidadStock,Producto_idProducto")] DetalleProducto detalleProducto)
        {
            if (ModelState.IsValid)
            {
                db.DetalleProducto.Add(detalleProducto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Producto_idProducto = new SelectList(db.Producto, "idProducto", "nombreProducto", detalleProducto.Producto_idProducto);
            return View(detalleProducto);
        }

        // GET: DetalleProductoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DetalleProducto detalleProducto = db.DetalleProducto.Find(id);
            if (detalleProducto == null)
            {
                return HttpNotFound();
            }
            ViewBag.Producto_idProducto = new SelectList(db.Producto, "idProducto", "Foto", detalleProducto.Producto_idProducto);
            return View(detalleProducto);
        }

        // POST: DetalleProductoes/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idDetalleProducto,Talla,CantidadStock,Producto_idProducto")] DetalleProducto detalleProducto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(detalleProducto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Producto_idProducto = new SelectList(db.Producto, "idProducto", "Foto", detalleProducto.Producto_idProducto);
            return View(detalleProducto);
        }

        // GET: DetalleProductoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DetalleProducto detalleProducto = db.DetalleProducto.Find(id);
            if (detalleProducto == null)
            {
                return HttpNotFound();
            }
            return View(detalleProducto);
        }

        // POST: DetalleProductoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DetalleProducto detalleProducto = db.DetalleProducto.Find(id);
            db.DetalleProducto.Remove(detalleProducto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineShoppingStore/Controllers/PaypalController.cs
using OnlineShoppingStore.Models;
using PayPal.Api;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShoppingStore.Controllers
{
    public class PaypalController : Controller
    {
        // GET: Paypal
        public ActionResult metodoPaypal()
        {
            APIContext apiContext = PaypalConfiguration.GetAPIContext();
            try
            {
                //A resource representing a Payer that funds a payment Payment Method as paypal
                //Payer Id will be returned when payment proceeds or click to pay
                string payerId = Request.Params["PayerID"];
                if (string.IsNullOrEmpty(payerId))
                {
                    //this section will be executed first because PayerID doesn't exist
                    //it is returned by the create function call of the payment class
                    // Creating a payment
                    // baseURL is the url on which paypal sendsback the data.
                    string baseURI = Request.Url.Scheme + "://" + Request.Url.Authority + "/Home/metodoPaypal?";
                    //here we are generating guid for storing the paymentID received in session
                    //which will be used in the payment execution
                    var guid = Convert.ToString((new Random()).Next(100000));
                    //CreatePayment function gives us the payment approval url
                    //on which payer is redirected for paypal account payment
                    var createdPayment = this.CreatePayment(apiContext, baseURI + "guid=" + guid);
                    //get links returned from paypal in response to Create function call
                    var links = createdPayment.links.GetEnumerator();
                    string paypalRedirectUrl = null;
                    while (links.MoveNext())
                    {
                        Links lnk = links.Current;
                        if (lnk.rel.ToLower().Trim().Equals("approval_url"))
                        {
                            //saving the payapalredirect URL to which user will be redirected for payment
                            paypalRedirectUrl = lnk.href;
                        }
                    }
                    // saving the paymentID in the key guid
                    Session.Add(guid, createdPayment.id);
                    return Redirect(paypalRedirectUrl);
                }
                else
                {
                    // This function exectues after receving all parameters for the payment
                    var guid = Request.Params["guid"];
                   // var executedPayment = ExecutePayment(apiContext, payerId, Session[guid] as string);
                    //If executed payment failed then we will show payment failure message to user
                    if (executedPayment.state.ToLower() != "approved")
                    {
                        return View("FailureView");
                    }
                }
            }
            catch (Exception ex)
            {
                return View("FailureView");
            }
            //on successful payment, show success page to user.
            return View("SuccessView");
        }

       

        private Payment CreatePayment(APIContext apicontext, string redirectURl)
        {

            var ItemLIst = new ItemList()
            {
                items = new List<Item>()
            };

            if (Session["cart"] != "")
            {
                List<Models.Home.Item> cart = (List<Models.Home.Item>)(Session["cart"]);
                foreach (var item in cart)
                {
                    ItemLIst.items.Add(new Item()
                    {
                        name = item.Product.ProductName.ToString(),
                        currency = "TK",
                        price = item.Product.Price.ToString(),
                        quantity = item.Product.Quantity.ToString(),
                        sku = "sku"
                    });


                }


                var payer = new Payer() { payment_method = "paypal" };

                var redirUrl = new RedirectUrls()
                {
                    cancel_url = redirectURl + "&Cancel=true",
                    return_url = redirectURl
                };

                var details = new Details()
                {
                    tax = "1",
                    shipping = "1",
                    subtotal = "1"
                };

                var amount = new Amount()
                {
                    currency = "USD",

                    total = Session["SesTotal"].ToString(),
                    details = details
                };

                var transactionList = new List<Transaction>();
                transactionList.Add(new Transaction()
                {
                    description = "Transaction Description",
                    invoice_number = "#100000",
                    amount = amount,
                    item_list = ItemLIst

                });

                this.payment = new Payment()
                {
                    intent = "sale",
                    payer = payer,
                    transactions = transactionList,
                    redirect_urls = redirUrl
                };
            }



            return this.payment.Create(apicontext);

        }
    }
}

OnlineShoppingStore/Controllers/ProductosController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineShoppingStore.DAL;
using System.Threading.Tasks;
using OnlineShoppingStore.Models;

namespace OnlineShoppingStore.Controllers
{
    public class ProductosController : Controller
    {
        private VentasEntities1 db = new VentasEntities1();

        // GET: Productos
        public ActionResult Index()
        {
            var producto = db.Producto.Include(p => p.Categoria);
            

            return View(producto.ToList());
        }
        //filtro por categoria
        public ActionResult OrdenarPorCategoria()
        {
            var productos = from p in db.Producto
                            orderby p.precio ascending
                            select p;
            return View(productos);
       
        }
        public ActionResult filtrar(string nombre)
        {
            var filtro = db.Producto.Where(tipo => tipo.Categoria.tipoCategoria.Equals(nombre));
            return View(filtro);
        }

      
        public ActionResult AddToCart(int? id)
        {
            if (Session["cart"] == null)
            {
                List<Carrito> cart = new List<Carrito>();
                var product = db.Producto.Find(id);
                cart.Add(new Carrito()
                {
                    Productos = product,
                    Cantidad = 1
                });
                Session["cart"] = cart;
            }
            else
            {
                List<Carrito> cart = (List<Carrito>)Session["cart"];
                var product = db.Producto.Find(id);
                cart.Add(new Carrito()
                {
                    Productos = product,
                    Cantidad = 1
                });
                Session["cart"] = cart;
            }
            return Redirect("../../Productos/IndexClient");
        }

        public ActionResult DetalleCarrito()
        {

            return View();
        }

        //Lista productos para usuario
        public ActionResult IndexClient()
        {
            var producto = db.Producto.Include(p => p.Categoria);


            return View(producto.ToList());
        }

        // GET: Productos/Details/5

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Producto.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        // GET: Productos/Create
        public ActionResult Create()
        {
            ViewBag.Categoria_idCategoria = new SelectList(db.Categoria, "idCategoria", "tipoCategoria");
            return View();
        }

        // POST: Productos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idProducto,Foto,nombreProducto,precio,Descripcion,Categoria_idCategoria")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                db.Producto.Add(producto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Categoria_idCategoria = new SelectList(db.Categoria, "idCategoria", "tipoCategoria", producto.Categoria_idCategoria);
            return View(producto);
        }

        // GET: Productos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Producto.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            ViewBag.Categoria_idCategoria = new SelectList(db.Categoria, "idCategoria", "tipoCategoria", producto.Categoria_idCategoria);
            return View(producto);
        }

        // POST: Productos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idProducto,Foto,nombreProducto,precio,Descripcion,Categoria_idCategoria")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(producto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Categoria_idCategoria = new SelectList(db.Categoria, "idCategoria", "tipoCategoria", producto.Categoria_idCategoria);
            return View(producto);
        }

        // GET: Productos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Producto.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        // POST: Productos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Producto producto = db.Producto.Find(id);
            db.Producto.Remove(producto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineShoppingStore/Views/Productos/Create.cshtml
@model OnlineShoppingStore.DAL.Producto

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container-fluid">
    <!-- Breadcrumbs-->

    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item ">Categorías</li>
        <li class="breadcrumb-item active">Crear Categoría</li>


    </ol>
    <!-- DataTables Example -->
    <div class="card mb-3">
        <div class="card-header">
            <i class="fas fa-table"></i>
            Crear Categoría

        </div>


        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Producto</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Foto, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.nombreProducto, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.nombreProducto, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.nombreProducto, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Categoria_idCategoria, "Categoria_idCategoria", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("Categoria_idCategoria", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Categoria_idCategoria, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Guardar" class="btn btn-success" />
                        @Html.ActionLink("Atrás", "Index", null, new { @class = "btn btn-info" })

                    </div>
                </div>
            </div>
        }
    </div>
</div>
        
        

OnlineShoppingStore/Views/Productos/Delete.cshtml
@model OnlineShoppingStore.DAL.Producto

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container-fluid">
    <!-- Breadcrumbs-->

    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item ">Producto</li>
        <li class="breadcrumb-item active">Eliminar Producto</li>


    </ol>
    <!-- DataTables Example -->
    <div class="card mb-3">
        <div class="card-header">
            <i class="fas fa-table"></i>
            Eliminar Producto
        </div>
        <div class="card-body">
            <h4>Producto</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    Foto
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Foto)
                </dd>

                <dt>
                    Nombre
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.nombreProducto)
                </dd>

                <dt>
                    Precio
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.precio)
                </dd>

                <dt>
                    Descripción
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Descripcion)
                </dd>

                <dt>
                    Categoria
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Categoria.tipoCategoria)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Eliminar" class="btn btn-danger" /> 
                    @Html.ActionLink("Atrás", "Index",null,new {@class="btn btn-info"})
                </div>
            }
        </div>
    </div>
</div>

OnlineShoppingStore/Views/Productos/Details.cshtml
@model OnlineShoppingStore.DAL.Producto

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Producto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Foto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Foto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nombreProducto)
        </dt>
        <dd class="Tallas">

            @{ Html.RenderAction("detalleProducto", "DetalleProductoes", new { id = Model.idProducto });}
        </dd>
        <dd>
            @Html.DisplayFor(model => model.nombreProducto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.precio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categoria.tipoCategoria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria.tipoCategoria)
        </dd>

    </dl>

    <p>

        @using (Html.BeginForm("AddToCart", "Productos", new { id = Model.idProducto }, FormMethod.Post))
        {
            <button value="Agregar a carrito" type="submit" class="pull-right"><i class="fa fa-shopping-cart"></i></button>
        }

        
        @Html.ActionLink("Detalle de Carrito", "../Productos/DetalleCarrito")
    </p>
    </div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.idProducto }) |
    @Html.ActionLink("Back to List", "Index")
</p>

OnlineShoppingStore/Views/Productos/DetalleCarrito.cshtml
@using OnlineShoppingStore.Models;
@{
    ViewBag.Title = "DetalleCarrito";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@if (Session["cart"] == null)
{
    <div class="alert alert-danger">
        <strong>No product added to cart!</strong>
    </div>

}
else
{
    <table class="table table-bordered" style="
    border-top-width: 105px;">
        <thead>
            <tr>
                <th>Product</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Line Total</th>

            </tr>
        </thead>
        <tbody>
            @{
                int Total = 0;
            }
            @foreach (Carrito item in (List<Carrito>)Session["cart"])
            {
                int lineTotal = Convert.ToInt32(item.Cantidad * item.Productos.precio);
                Total = Convert.ToInt32(@Total + lineTotal);
                <tr>
                    <td>@item.Productos.nombreProducto</td>
                    <td>@item.Productos.precio</td>
                    <td>@item.Cantidad</td>
                    <td>@lineTotal</td>
                </tr>
            }

            <tr>
                <td colspan="4" class="text-right"><b>Total: @Total</b></td>
            </tr>
        </tbody>
    </table>
    <a href="@Url.Action("metodoPaypal", "Paypal")" class="btn btn-success">Pagar >></a>

}

OnlineShoppingStore/Views/Productos/Edit.cshtml
@model OnlineShoppingStore.DAL.Producto

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container-fluid">
    <!-- Breadcrumbs-->

    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item ">Productos</li>
        <li class="breadcrumb-item active">Modificar Productos</li>


    </ol>
    <!-- DataTables Example -->
    <div class="card mb-3">
        <div class="card-header">
            <i class="fas fa-table"></i>
            Modificar Producto

        </div>
        <div class="card-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Producto</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.idProducto)

                    <div class="form-group">
                        @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Foto, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.nombreProducto, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.nombreProducto, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.nombreProducto, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Categoría", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("Categoria_idCategoria", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Categoria_idCategoria, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <a onclick="window.history.back();" class="btn btn-info">Cancelar</a>

                    <input type="submit" value="Guardar" class="btn btn-success" />
                </div>
            }

        </div>
    </div>
    
</div>
        

OnlineShoppingStore/Views/Productos/IndexClient.cshtml
@model IEnumerable<OnlineShoppingStore.DAL.Producto>

@{
    ViewBag.Title = "IndexClient";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<div class="Categorias">
    
    @{ Html.RenderAction("MostrarCategoria", "Categorias");}
</div>

<div class="row product-container" style="margin-top:-155px; margin-left:400px;">

    @foreach (var item in Model)
    {

        <div class="col-md-3 col-sm-3 col-xs-6" style="margin-bottom:8px">
            <a href=@("../Productos/Details/"+item.idProducto)>
                <div class="thumbnail product-item" style="height:450px; width:250px;">



                    <div class="caption">


                        <img class="img-responsive" title="Click to View Product detail"
                             style="cursor:pointer;height:400px;width:400px"
                             src="~/Images/mesa-restaurante.png" />

                        @Html.DisplayFor(modelItem => item.Foto)


                        @Html.DisplayFor(modelItem => item.nombreProducto)


                        @Html.DisplayFor(modelItem => item.precio)


                        @Html.DisplayFor(modelItem => item.Descripcion)

                        @Html.DisplayFor(modelItem => item.Categoria.tipoCategoria)




                    </div>
                </div>
            </a>
        </div>
    }
</div>